apiVersion: v1
kind: Namespace
metadata:
  name: tls-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickle-api
  namespace: tls-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickle-api
  template:
    metadata:
      labels:
        app: quickle-api
    spec:
      containers:
      - name: quickle-api
        image: lukasblaha/quickle-api:1.0.0-arm64
        imagePullPolicy: IfNotPresent
        env:
          - name: DSN
            value: "host=quickle-postgres port=5432 user=postgres password=postgres dbname=quickle sslmode=disable timezone=UTC connect_timeout=5"
        ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: quickle-api
  namespace: tls-services
spec:
  selector:
    app: quickle-api
  ports:
    - port: 8888
      targetPort: 80
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: quickle-api
  namespace: tls-services
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host("quickle-api.fikos.cz")
    services:
    - name: quickle-api
      port: 8888
  tls:
    secretName: mytls
