apiVersion: v1
kind: Namespace
metadata:
  name: tls-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickle-postgres
  namespace: tls-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickle-postgres
  template:
    metadata:
      labels:
        app: quickle-postgres
    spec:
      containers:
      - name: quickle-postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: quickle
        ports:
          - containerPort: 5432
            protocol: TCP
        volumeMounts:
        - name: quickle-data
          mountPath: /var/lib/potgresql/data
      restartPolicy: Always
      volumes:
      - name: quickle-data
        hostPath:
          path: /data/quickle/postgres
---
apiVersion: v1
kind: Service
metadata:
  name: quickle-postgres
  namespace: tls-services
spec:
  selector:
    app: quickle-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
